config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  namespace :api do
    resources :users, only: [:create]
    resources :products, only: [:create, :show, :index, :destroy, :update]
    resources :likes, only: [:create, :show, :index, :destroy]
    resources :orders, only: :index
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users
  
  root "products#index"

  get "/products/:id/sell", to: "products#sell_details"
  get "/products/:id/buy", to: "products#buy_details"
  put "/products/:id/buy", to: "products#buy"
  get "/products/sell", to: "products#sell_list"

  resources :products do
    resources :feedbacks
  end
  resources :orders
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many :orders
    has_many :users, through: :orders    
    has_many :feedbacks
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    validates :name, presence: true
    validates :category, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 20.0}
    validates :quantity, presence: true, numericality: { greater_than: 0}, on: :create

    scope :filter_by_category, -> (category) {where("category like ?", category)}
    scope :filter_by_price, -> (price) {where("price <= ?", price)}
end

app/controllers/api/products_controller.rb
class Api::ProductsController < Api::ApplicationController
  before_action :current_user

  def index
    begin
    if params[:type] == "buy"
      products = Product.where(status: true, isAvailable: true).where.not(user_id: @current_user.id)
      render json: {data: products, status: true}
    elsif params[:type] == "sell"
      products = @current_user.products
      render json: {data: products, status: true}
    else
      render json: {error: "Invalid params", status: false}, status: 400
    end
    rescue => exception
      render json: {error: exception, status: false}, status: 500
    end
  end

  def show
    begin
      product = Product.find(params["id"])
      if product
        render json: {data: product, status: true}, status: 200
      else
        render json: {error: "Invalid product id",status: false}, status: 400
      end
    rescue => exception
      render json: {error: exception, status: false}, status: 500
    end
  end

  def create
    begin
      @product = Product.create(name: params["name"], category: params["category"], price: params["price"], status: true, user_id: @current_user.id, quantity: params["quantity"], isAvailable: true)
      if @product.save
        render json: {status: true}, status: 200
      else 
        render json: {error: "Failed to create product", status: false}, status: 400
      end
    rescue => exception
      render json: {error: exception, status:false}, status: 500
    end
  end

  def update
    begin
    product = Product.find(params[:id])
    if product
      if product.user_id == @current_user.id
        product.update(product_params)
        product.update_attribute(:status, product.quantity > 0)
        render json: {status: true}, status: 200
      else
        render json: {error: "Unauthorized access", status: false}, status: 401
      end
    else
      render json: {error: "Invalid product id", status: false}, status: 400
    end
    rescue => exception
      puts exception
      render json: {error: exception, status: false}, status: 500
    end
  end

  def destroy
    begin
      product = Product.find(params[:id])
      if product
        if product.user_id == @current_user.id
          product.destroy!
          render json: {status: true}, status: 200
        else
          render json: {error: "Unauthorized access", status: false}, status: 401
        end
      else
        render json: {error: "Invalid product id", status: false}, status: 400
      end
    rescue => exception
      render json: {error: exception, status:false}, status: 500
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :category, :price, :quantity)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_user, on: [:new, :index, :edit, :destroy, :buy]

  def home
    if user_signed_in?
      @wallet = current_user.wallet
    end
  end

  def new
    @product = Product.new
  end

  def create
    begin
      @product = Product.create(name: params["product"]["name"], category: params["category"], price: params["product"]["price"], status: true, user_id: current_user.id, quantity: params["product"]["quantity"], isAvailable: true)
      if @product.save
        redirect_to '/products/sell'
      else 
        render :new
      end
    rescue => exception
      puts exception
      render :new, status: :unprocessable_entity
    end
  end

  def index
    puts params
    @products = Product.where(status: true, isAvailable: true).where.not(user_id: current_user.id)
    if params.has_key?(:category)
      @products = @products.filter_by_category(params[:category])
    end
    if params.has_key?(:price) && params[:price].to_i != 0
      @products = @products.filter_by_price(params[:price])
    end
  end

  def sell_list
    @products = current_user.products.where(user_id: current_user.id).where(isAvailable: true)
  end

  def show
    @product = Product.find(params[:id])
  end

  def sell_details
    @product = Product.find(params[:id])
  end

  def buy_details
    @product = Product.find(params[:id])
    @like = current_user.likes.where(product_id: @product.id)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(name: params["product"]["name"], category: params["category"], price: params["product"]["price"], quantity: params["product"]["quantity"], status: params["product"]["quantity"].to_i > 0)
      redirect_to "/products/#{@product.id}/sell"
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.update_attribute(:isAvailable, false)
    # @product.destroy! 
    redirect_to '/products/sell'
  end

  def buy
    quantity = params["quantity"]
    @product = Product.find(params[:id])
    if quantity == ""
      flash.alert = "Quantity Cannot Be Empty"
      redirect_to "/products/#{@product.id}/buy"
    elsif quantity.to_i == 0
      flash.alert = "Invalid quantity"
      redirect_to "/products/#{@product.id}/buy"
    elsif quantity.to_i > @product.quantity
      flash.alert = "Required Quantity Not Available"
      redirect_to "/products/#{@product.id}/buy"
    else
      val = current_user.wallet.coins * quantity.to_f
      if val < @product.price
        flash.alert = "Wallet Doesn't Have Enough Coins"
        redirect_to "/products/#{@product.id}/buy"
      else
        buy_product quantity
        create_order_history quantity
      end
    end
  end

  private
    def product_params
      params.permit(:name, :category, :price, :quantity)
    end

    def check_user
      if !user_signed_in?
        redirect_to new_user_session_path
      end
    end

    def buy_product(quantity)
      val = current_user.wallet.coins
      price = @product.price * quantity.to_i
      current_user.wallet.update_attribute(:coins, val - price)
      @user = User.find_by(id: @product.user_id)
      val = @user.wallet.coins
      @user.wallet.update_attribute(:coins, val + price)
      @product.update_attribute(:quantity, @product.quantity - quantity.to_i)
      if @product.quantity == 0
        @product.update_attribute(:status, false)
      end
    end

    def create_order_history(quantity)
      @order = Order.find_by(user_id: current_user.id, product_id: @product.id)
      if @order != nil
        @order.update_attribute(:quantity, @order.quantity + quantity.to_i)
      else
        print @order.methods
        @order = Order.create(quantity: 1, user_id: current_user.id, product_id: @product.id)
        @order.save
      end
        redirect_to '/products?type=buy'
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_filters.html.erb
<div style="width: 20%; display: flex; justify-content: center; margin: 50px 10px 0;">
<%= form_with url: '/products', method: :get,  id: "filter", name: "filter" do |form| %>
        <%= form.label :category %>
        <%= select_tag(:category, options_for_select(['Women Accessories','Electronics','Footwear','Electrical Appliances', 'School Supplies'],params[:category]), {:class => 'dropdown form-control', :style => "width: 200px;border-radius: 14px"}) %>
        <br><br>
  <%= form.label "Max Price " %> <span id="value"></span> <br>
  20 <%= form.range_field :price, :in => 0..100, :step => '10',id: "price",name:"price", :value => params[:price] %> 100
    <div style="margin-top: 20px">
        <%= form.submit "Filter", class: 'btn btn-primary', style: 'height: 30px;padding: 0 13px;border-radius: 24px;' %>
        <%= link_to "clear", "/products", method: :get%>
</div>
<% end %>
</div>
<script>
let isDirty = false;
let isCategory = false;
 $('#price').click(function(e){
   isDirty=true;
   console.log(e.target.value);
   $('#value').text(e.target.value);
  });
  $('#category').click(function(){
    isCategory = true;
  })
  $('#filter').submit(function(e){
    e.preventDefault();
    console.log(e);
    if(!isCategory){
      $('#category').val("");
    }
    if(!isDirty){
      console.log($("#filter"))
      $("#price").val(0);
      console.log($("#price").val());
    }
    $("#filter").off("submit")
    $(this).submit();
  })
  </script>

app/views/products/_form.html.erb
<div class="form-group form">
<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control' %>
    <% @product.errors[:name].any? %>
      <% @product.errors[:name].each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= select_tag(:category, options_for_select(['Women Accessories','Electronics','Footwear','Electrical Appliances', 'School Supplies'],@product.category), {:class => 'dropdown form-control'}) %>
    <% @product.errors[:category].any? %>
      <% @product.errors[:category].each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price, class: 'form-control' %>
    <% @product.errors[:price].any? %>
      <% @product.errors[:price].each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>
  <div>
    <%= form.label :quantity %><br>
    <%= form.text_field :quantity, class: 'form-control' %>
    <% @product.errors[:quantity].any? %>
      <% @product.errors[:quantity].each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>
  <div style="margin-top: 20px">
    <%= form.submit submit_text, class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/products/_product_details.html.erb
<div class="card product" style="width: 340px;">
  <div class="card-body">
    <h5 class="card-title"><%= product.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= product.category %></h6>
    <p class="card-text">Price: <%= product.price %></p>
    <p class="card-text">Availability: <%= product.quantity %></p>
    <% if show_status %>
      <% if @product.status? %>
        <p class="card-text">Status: Not Sold Yet</p>
      <% else %>
        <p class="card-text">Status: Sold</p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/buy_details.html.erb
<div class="wrapper">
    <h3>Product Details</h3>
    <%= render "product_details", product: @product, show_status: false %>
    <div class="form">
        <%= form_with url: "/products/#{@product.id}/buy", method: :put do |form| %>
            <div style="width: 340px; margin: 10px auto;" class="input-group">
                <%= form.text_field :quantity, class: 'form-control', placeholder: 'Quantity' %>
            <div class="input-group-append">
                <%= form.submit "Buy", class: 'btn btn-outline-primary' %>
            </div>
                        </div>
        <% end %>
    </div>  
    <br>
    <div style="width: 340px; margin: 0 auto;">
        <% if @product.feedbacks.count != 0 %>
            <h4>Reviews</h4>
            <%= render @product.feedbacks %>
        <% end %>
        <%= link_to "Go Back", "/products?type=buy" %>
    </div>
</div>

app/views/products/edit.html.erb
<div class="wrapper">
<h3 style="text-align: center">Sell Your Product</h3>
<%= render "form", product: @product, submit_text: "Update Product" %><br>
<div style="width: 275px; margin: 0 auto">
<%= link_to "Go Back", "/products/sell" %>
</div>

app/views/products/home.html.erb
<% if user_signed_in? %>
<div class="container">
    <div>Your Wallet: <%= current_user.wallet.coins %></div>
</div>
<% end %>

app/views/products/index.html.erb
<div style="display: flex; height: calc(100% - 60px);">
<%= render "filters", product: @product%>
<div style="width: 70%">
<h3>Products List</h3>
<% if @products.count > 0 %>
<div class="container" style="align-items: flex-start">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Product Name </th>           
      <th scope="col">Product Category </th>        
      <th scope="col">Price </th>      
      <th scope="col"></th>
    </tr>
  </thead>
  </tbody>
 <% @products.each do |product| %>
  <tr scope="row">
    <td><%= product.name%></td>   
    <td><%=product.category %></td>
    <td><%=product.price %></td>
    <td><%= link_to "View", "/products/#{product.id}/buy" %></td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>
<% end %>
</div>
</div>

app/views/products/new.html.erb
<div class="wrapper">
<h3 style="text-align: center">Sell Your Product</h3>
<%= render "form", product: @product, submit_text: "Sell Product" %>
</div>

app/views/products/sell_details.html.erb
<div class="wrapper">
<h3>Product Details</h3>
<%= render "product_details", product: @product, show_status: true %>
<div style="width: 340px; margin: 0 auto;">
    <% if @product.feedbacks.count != 0 %>
        <br><h4>Reviews</h4>
        <%= render @product.feedbacks %>
    <% end %>
    <% if @product.status %>
        <div style="width: 340px; margin: 0 auto;"><%= button_to "Delete", "/products/#{@product.id}", method: :delete, class: 'link' %></div>
    <% end %>
    <%= link_to "Edit", edit_product_path(@product), class: 'link' %><br>
    <%= link_to "Go Back", "/products/sell", class: 'link' %>
</div>
</div>

app/views/products/sell_list.html.erb
<div class="wrapper">
<h3>Your Selling History</h3>
<% if @products.count > 0 %>
<div class="container" style="align-items: flex-start">
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Product Id</th>           
            <th scope="col">Product Name</th>
            <th scope="col">Status</th>       
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <% @products.each do |product| %>
            <tr scope="row">
                <td><%= product.id %></td>   
                <td><%=product.name %></td>
                <% if product.status? %>
                    <td>Not Sold Yet</td>
                <% else %>
                    <td>Sold</td>
                <% end %>
                <td><%= link_to "View", "/products/#{product.id}/sell" %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>
<% end %>
</div>

app/views/products/show.html.erb
<div class="wrapper">
    <h3>Product Details</h3>
    <div class="card product" style="width: 340px;">
        <div class="card-body">
            <h5 class="card-title"><%= @product.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= @product.category %></h6>
            <p class="card-text">Price: <%= @product.price %></p>
        </div>
    </div>
    <% if @product.feedbacks.count != 0 %>
    <div style="width: 340px; margin: 0 auto;">
        <h4>Reviews</h4>
        <%= render @product.feedbacks %>
    </div>
    <% end %>
    <%= render 'feedbacks/form' %>
    <div  style= 'width: 340px; margin: 0 auto;'>
        <%= link_to "Go Back", "/orders" %>
    </div>
</div>